spring:
  application:
    name: business
server:
  port: 8000

ai:
  providers:
    ollama:
      url: http://localhost:11434
      endpoints:
        chat: /v1/chat/completions
        embedding: /v1/embeddings
    bailian:
      url: https://dashscope.aliyuncs.com
      api-key: ${BAILIAN_API_KEY:}
      endpoints:
        chat: /compatible-mode/v1/chat/completions
        rerank: /api/v1/services/rerank/text-rerank/text-rerank
    aihubmix:
      url: https://aihubmix.com
      api-key: ${AIHUBMIX_API_KEY:}
      endpoints:
        chat: /v1/chat/completions
        embedding: /v1/embeddings
    siliconflow:
      url: https://api.siliconflow.cn
      api-key: ${SILICONFLOW_API_KEY:}
      endpoints:
        chat: /v1/chat/completions
        embedding: /v1/embeddings